### ISSUE TITLE
TypeScriptの導入の是非

### ISSUE THREAD

**Issue by shiro83** [nw-web-d/d_book_clone#2]
**TypeScriptを導入するかどうか？現状はしていない。**

結論的には以下の利点があり導入した方がよい
- 今風
- 型指定ができることにより、利点が生まれる
- Vue.jsのコーディング規約がエグいほど厳しいが、TypeScriptを通せばかなり緩和される。（発狂しそうな規約はTypeScript→JavaScript変換の時によしなにやってくれる）

しかし、プロトタイプということで最小限の構成にしたかったため入れてない。
実際のプロジェクトでもTypeScriptを導入するのであれば入れてもよいかも。

**Comment by higexxp** [comment]
Typescriptはコードの可読性が上がるので、多人数がいじるような実際のPJでは、入れない手は無いと思います

**Comment by shiro83** [comment]
了解ですー
プロタイプにも入れるように検討しますー
