### ISSUE TITLE
UnitTestツールの導入の是非について

### ISSUE THREAD

**Issue by shiro83** [nw-web-d/d_book_clone#3]
個人的は画面処理には必要ない
理由は以下
- 画面に表示されないタグの数やclassの設定値をテストして何の意味がある？
- 画面は変更が激しいのでtestケースを作るのは不毛
- ABテストとかやる時に２つとも作るの？バカなの？

サーバーサイドであればやる価値はある

**Comment by higexxp** [comment]
昨年のVue導入検討時に、チーム内で検討した結果
上記と同じ意見がでて、画面についてはUnitTestは導入しないということになりました
ただ、リリース後のデグレ事故がけっこう起きるので、何か拾える仕組みは必要と考えてます

**Comment by shiro83** [comment]
どうのような事故が多いかによりますねぇ、事故統計と原因分析してその結果次第ではSeleniumとかですかね。

**Comment by higexxp** [comment]
よく起きるのは以前追加したclass指定が消えて画面が動いてなかったとかですかね

**Comment by shiro83** [comment]
画面の最終確認はデザナーさん（それか発案者）ですね？

デザイナーさんは自分のデザインの確認を間違うことは滅多にないので、
修正がそれ以外の部分にまで影響を及ぼしていると予想します。

VueやReactなど画面をコンポーネント単位で分割できるアーキテクチャのフレームワークであれば、修正の副作用をかなり絞り込めると思います。（あくまで作り方次第ですが。。。。）

自動テストなどを導入しなくても、新アプリに移行すれば、現状のデグレ問題は多少緩和されると思います。
