### ISSUE TITLE
cssのフレームワークについて

### ISSUE THREAD

**Issue by shiro83** [nw-web-d/d_book_clone#4]
とりあえずBootstrapを入れているがどうしよう。。。。

**Comment by higexxp** [comment]
やり込むんだったらcssフレームワーク無しでと言いたいところですが
cssの心得が無い我々だとそれは難しいので、なんか適当なものをチョイスすれば良いかなと思います。
遊び案件でvueやったときVuetifyとか使いましたね

**Comment by shiro83** [comment]
@higexxp 
ということは現行ではBootstrapなしで作っているということですか？

**Comment by higexxp** [comment]
現行はフレームワークは使ってないですね

**Comment by shiro83** [comment]
なるほどー
cssやhtmlはデザナーがやる感じですか？

**Comment by higexxp** [comment]
デザイナーですね
基本的にcssフレームワークはかゆいところに手が届かなかったり
パフォーマンスがイマイチなので、ecのフロントではあまり使わないと思います

**Comment by shiro83** [comment]
デザイナーが作るなら、フレームワークを検討する必要はないですね。
後からデザイナーが好きなのを使ってもらえば
